name: create-release
# create release and tag in GitHub

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  create-release-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create a release
    steps:
      - name: checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: create GH release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git fetch --tags
          latest_tag_version=$(git describe --tags --abbrev=0)
          echo "Found release ${latest_tag_version} as previous git tag"
          version=$(echo $latest_tag_version | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
          echo "Create release ${version} for ${GITHUB_REPOSITORY} in GitHub"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/releases \
            -f tag_name=$version \
            -f name="v$version" \
            -F draft=false \
            -F prerelease=false \
            -F generate_release_notes=true
