name: test-release

# publish to test.pypi.org on merge to default branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  test-publish-main:
    environment: test-release  # match name in test.PyPI.org OIDC
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: setup rye
        uses: eifinger/setup-rye@v3
      - name: set python version
        run: rye pin "3.12"
      - name: create GH release
        run: |
          git fetch --tags
          old_version=$(git describe --tags --abbrev=0)
          echo "Last tag was ${old_version}"
          version=$(echo $old_version | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
          echo "For ${GITHUB_REPOSITORY} creating release ${version}"

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/releases \
            -f tag_name=$version \
            -f name="v$version" \
            -F draft=false \
            -F prerelease=false \
            -F generate_release_notes=true
      - name: build package
        run: rye build
      - name: publish to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
