name: test-release

# publish to test.pypi.org on merge to default branch

on:
  push:
    branches:
      - 'main'

jobs:
  test-publish:
    environment: test-release  # match name in test.PyPI.org OIDC
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
      - run: rye pin "3.12"
      - run: rye build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
